#!/bin/bash

set -x

if [ "$#" -ne 4 ]; then
  echo "Usage: ./bench MAX_THREADS N_OPS N_RUNS N_POOL_LINES"
  exit 1
fi
  
MAX_THREADS="$1"
N_OPS="$2"
N_RUNS="$3"
N_POOL_LINES="$4"

mkdir -p data

# reserve at least 2 CPUs for other users
CPUS=$(echo "$(grep -c 'processor' /proc/cpuinfo) - 2" | bc)

if [ $MAX_THREADS -gt $CPUS ]; then
  echo "Too many threads, we only have $CPUS CPUs" >&2
  exit 1
fi

FILE="bench_t${MAX_THREADS}_$(date +%F_%H-%M-%S).csv"
DATA="data/${FILE}"

time ./test $MAX_THREADS $CPUS $N_OPS $N_RUNS $N_POOL_LINES | grep -o '[^ ,]*,[^ ,]*,[^ ,]*,[^ ,]*,[^ ,]*,[^ ,]*' > ${DATA}

# generate graphs
Rscript graph.r ${DATA}
