#!/bin/bash

set -x

if [ "$#" -ne 4 ]; then
  echo "Usage: ./bench MAX_THREADS N_OPS N_RUNS N_POOL_LINES"
  exit 1
fi
  
 
MAX_THREADS="$1"
N_OPS="$2"
N_RUNS="$3"
N_POOL_LINES="$4"

# reserve at least 2 CPUs for other users
CPUS=$(echo "$(grep -c 'processor' /proc/cpuinfo) - 2" | bc)

time ./test $MAX_THREADS $CPUS $N_OPS $N_RUNS $N_POOL_LINES
