#!/bin/bash

LITMUS="$1"
BNAME=$(basename "$LITMUS")
NAME="${BNAME%.litmus}"
DOT="${NAME}.dot"
PDF="${NAME}.pdf"
PDOT="dot/$DOT"
PPDF="pdf/$PDF"

mkdir -p dot pdf
rm -f "$PDOT"
herd7 -conf linux-kernel.cfg -skipchecks happens-before,propagation,coherence,rcu -o dot "$LITMUS"
if [ -s "$PDOT" ]; then
  dot -Tpdf "$PDOT" -o "$PPDF"
  echo "generated $PPDF"
else
  echo "graph generation failed"
fi
